/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fEL58fwRSG4
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardTitle, CardContent, Card } from "@/components/ui/card"
import 'primeicons/primeicons.css';
import './styles.css';




export default function landing() {
  return (
    (<div className="max-w-screen mx-auto">
      <header className="flex justify-around items-center p-2  bg-[#0f172a] text-white">
       <img src="https://fakeimg.pl/100x50" alt="logo" />
        <nav className="flex space-x-4 navbar">
          <Link className="text-white hover:text-[#009574]" href="#">
            INICIO
          </Link>
          <Link className="text-white hover:text-[#009574]" href="#">
            SERVICIOS
          </Link>
          <Link className="text-white hover:text-[#009574]" href="#">
            CONTACTO
          </Link>
          <Link className="text-white hover:text-[#009574]" href="#">
            CLIENTES
          </Link>
          <Link className="text-white hover:text-[#009574]" href="#">
            AVISO DE PRIVACIDAD
          </Link>
          <Link className="text-white hover:text-[#009574]" href="#">
            INICIAR SESIÓN
          </Link>
        </nav>
      </header>
      <section className="text-center  bg-[#e2e8f0]">
        <img src="https://fakeimg.pl/1924x620" alt="" />
      </section>
      <section className="py-8 px-4">
        <h2 className="text-2xl font-bold mb-10 text-center">Educación <span className='text-[#009574]'>Continua</span></h2>
        <p className="text-gray-700 mb-8 text-center text-sm text-justify px-20">
          La Universidad Tecnológica Emiliano Zapata, es una Universidad pública con 22 años de experiencia que forma
          parte de la Dirección General de Universidades Tecnológicas y Politécnicas de la SEP. A través del
          Departamento de Educación Continua ofrece servicios de capacitación educativa y profesional, de acuerdo al
          avance y desarrollo de todos los campos del saber, con la finalidad de dar respuesta a las necesidades de los
          sectores social, gubernamental y productivo de la región y del país.
        </p>
        <h3 className="text-2xl font-bold mb-10 text-center">Nuestros <span className='text-[#009574]'>Servicios</span></h3>
        <div className="grid grid-cols-3 gap-4 mb-8">
          <Card className="bg-[#009574]" >
            <CardContent>
              <CardTitle className='text-center mt-3 text-white'>CURSOS</CardTitle>
            </CardContent>
          </Card>
          <Card className="bg-[#1e293b]">
            <CardContent>
              <CardTitle className='text-center mt-3 text-white'>DIPLOMADOS</CardTitle>
            </CardContent>
          </Card>
          <Card className="bg-[#009574]">
            <CardContent>
              <CardTitle className='text-center mt-3 text-white'>TALLER</CardTitle>
            </CardContent>
          </Card>
        </div>
        <h3 className="text-2xl font-bold mb-4 text-center mt-20 ">Algunos de <span className='text-[#009574]'>nuestros clientes</span></h3>
        <div className="grid grid-cols-6 gap-4 mb-8">
          <img
            alt="TACHIS MEXICO"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100" />
          <img
            alt="SECRETARIA DE DESARROLLO SUSTENTABLE"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100" />
          <img
            alt="SAINT-GOBAIN"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100" />
          <img
            alt="FUNDACION COPARMEX"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100" />
          <img
            alt="CERVECERIA CUAUHTEMOC MOCTEZUMA"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100" />
          <img
            alt="DGETI"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100" />
          <img
            alt="CAPUFE"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100" />
          <img
            alt="MORELOS"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100" />
          <img
            alt="ISSSTE"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100" />
          <img
            alt="CECyTE"
            height="50"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/50",
              objectFit: "cover",
            }}
            width="100" />
        </div>
      </section>
      <footer className="bg-[#0f172a] text-white p-20">
        <div className="grid grid-cols-4 gap-2 mb-4">
          <div className='text-center'>
            <i className='pi pi-map-marker'></i>
            <p>Ubicación <br />Av. Universidad Tecnológica No. 1 Col. Palo Escrito, 62760, Emiliano Zapata, Morelos.</p>
          </div>
          <div className='text-center'>
            <i className='pi pi-phone'></i>
            <p>Contacto <br />777 01 03 28 777 361 61 15 ext. 280</p>
          </div>
          <div className='text-center'>
            <i className='pi pi-envelope'></i>
            <p>Correo electrónico <br /> educacioncontinua@utez.edu.mx</p>
          </div>
          <div className='text-center'>
            <i className='pi pi-clock'></i>
            <p>Horarios de atención <br />Lunes a viernes de 9:00 a 17:00</p>
          </div>

        </div>
        <hr className='w-100' />
        <div className="flex justify-center space-x-4 mb-4">

        </div>
        <p className="text-center text-sm">Desarrollado por CDTI. Todos los derechos reservados.</p>
      </footer>
    </div>)
  );
}


